[package]
name = "wiper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.142"
rand = "0.8.5"
tempfile = "3.5.0"
